In [158]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from xgboost import XGBRegressor
from sklearn.preprocessing import LabelEncoder

In [159]:
dataset= pd.read_excel("C:\\Users\\desum\\OneDrive\\Desktop\\Life Underwriting\\Premium Prediction Model\\Predict_Final.xlsx")
df=dataset

In [160]:
df.shape

(2090, 10)

In [161]:
df.drop(labels='Sl.No',axis=1, inplace=True)

In [162]:
df.head()

PolicyType  PolicyTerm  Gender  Age PremiumPayment  Sum Assured  \
0       Term          40    Male   22         Yearly      2000000   
1  Endowment          10    Male   49         Yearly      5000000   
2       Term          35  Female   33         Yearly      3500000   
3       Term          40  Female   21         Yearly      2500000   
4       Term          30  Female   31         Yearly      3000000   

      Occupation Smoker  Total Premium  
0        Student     No    2030.438032  
1       Salaried    Yes  302907.286978  
2       Salaried     No    8242.752196  
3        Student    Yes    2054.927549  
4  Self-Employed     No    6688.783291

In [163]:
df.tail()

PolicyType  PolicyTerm  Gender  Age PremiumPayment  Sum Assured  \
2085       Term          30  Female   34         Yearly      5000000   
2086       Term          30  Female   37         Yearly      5000000   
2087       Term          30  Female   41         Yearly      5000000   
2088       Term          30  Female   44         Yearly      5000000   
2089       Term          30  Female   47         Yearly      5000000   

      Occupation Smoker  Total Premium  
2085    Salaried    Yes      13901.991  
2086    Salaried    Yes      15403.823  
2087    Salaried    Yes      18345.093  
2088  Unemployed     No      12751.397  
2089  Unemployed     No      16178.973

In [164]:
df.shape

(2090, 9)

In [165]:
#categorical datas are (Object): 
#Type of Policy
#Gender
#Premium Payment
#Occupation
#Smoker
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2090 entries, 0 to 2089
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   PolicyType      2090 non-null   object 
 1   PolicyTerm      2090 non-null   int64  
 2   Gender          2090 non-null   object 
 3   Age             2090 non-null   int64  
 4   PremiumPayment  2090 non-null   object 
 5   Sum Assured     2090 non-null   int64  
 6   Occupation      2090 non-null   object 
 7   Smoker          2090 non-null   object 
 8   Total Premium   2090 non-null   float64
dtypes: float64(1), int64(3), object(5)
memory usage: 147.1+ KB


In [166]:
df['PolicyType'].unique()

array(['Term', 'Endowment'], dtype=object)

In [167]:
df['PolicyTerm'].unique()

array([40, 10, 35, 30, 15, 20, 25,  5], dtype=int64)

In [168]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [169]:
df['PremiumPayment'].unique()

array(['Yearly', 'Monthly'], dtype=object)

In [170]:
df['Occupation'].unique()

array(['Student', 'Salaried', 'Self-Employed', 'Retired', 'Agriculturist',
       'Unemployed'], dtype=object)

In [171]:
df.Occupation.value_counts()

Salaried         1262
Student           285
Self-Employed     233
Unemployed        165
Retired           106
Agriculturist      39
Name: Occupation, dtype: int64

In [172]:
df.describe()

PolicyTerm          Age   Sum Assured  Total Premium
count  2090.000000  2090.000000  2.090000e+03   2.090000e+03
mean     22.947368    38.666507  5.329179e+06   5.500443e+04
std      10.252770    12.257383  2.898475e+06   1.781536e+05
min       5.000000    20.000000  2.500000e+05   1.314516e+02
25%      15.000000    28.000000  3.000000e+06   2.820093e+03
50%      20.000000    38.000000  4.500000e+06   1.283609e+04
75%      30.000000    50.000000  8.000000e+06   4.025524e+04
max      40.000000    60.000000  1.000000e+07   4.472302e+06

In [173]:
df.to_csv('Premium Prediction.csv')

In [174]:
df.head()

PolicyType  PolicyTerm  Gender  Age PremiumPayment  Sum Assured  \
0       Term          40    Male   22         Yearly      2000000   
1  Endowment          10    Male   49         Yearly      5000000   
2       Term          35  Female   33         Yearly      3500000   
3       Term          40  Female   21         Yearly      2500000   
4       Term          30  Female   31         Yearly      3000000   

      Occupation Smoker  Total Premium  
0        Student     No    2030.438032  
1       Salaried    Yes  302907.286978  
2       Salaried     No    8242.752196  
3        Student    Yes    2054.927549  
4  Self-Employed     No    6688.783291

In [175]:
#'PolicyType','Gender','PremiumPayment','Occupation','Smoker'

In [176]:
le_policytype = LabelEncoder()
df['PolicyType'] = le_policytype.fit_transform(df['PolicyType'])
df['PolicyType'].unique()

array([1, 0])

In [177]:
le_gender = LabelEncoder()
df['Gender'] = le_gender.fit_transform(df['Gender'])
df['Gender'].unique()

array([1, 0])

In [178]:
le_premiumpayment = LabelEncoder()
df['PremiumPayment'] = le_premiumpayment.fit_transform(df['PremiumPayment'])
df['PremiumPayment'].unique()

array([1, 0])

In [179]:
le_occupation = LabelEncoder()
df['Occupation'] = le_occupation.fit_transform(df['Occupation'])
df['Occupation'].unique()

array([4, 2, 3, 1, 0, 5])

In [180]:
le_smoker = LabelEncoder()
df['Smoker'] = le_smoker.fit_transform(df['Smoker'])
df['Smoker'].unique()

array([0, 1])

In [181]:
df.head()

PolicyType  PolicyTerm  Gender  Age  PremiumPayment  Sum Assured  \
0           1          40       1   22               1      2000000   
1           0          10       1   49               1      5000000   
2           1          35       0   33               1      3500000   
3           1          40       0   21               1      2500000   
4           1          30       0   31               1      3000000   

   Occupation  Smoker  Total Premium  
0           4       0    2030.438032  
1           2       1  302907.286978  
2           2       0    8242.752196  
3           4       1    2054.927549  
4           3       0    6688.783291

# MODEL

In [182]:
X= df.drop(columns='Total Premium')
Y= df['Total Premium']

In [183]:
X

PolicyType  PolicyTerm  Gender  Age  PremiumPayment  Sum Assured  \
0              1          40       1   22               1      2000000   
1              0          10       1   49               1      5000000   
2              1          35       0   33               1      3500000   
3              1          40       0   21               1      2500000   
4              1          30       0   31               1      3000000   
...          ...         ...     ...  ...             ...          ...   
2085           1          30       0   34               1      5000000   
2086           1          30       0   37               1      5000000   
2087           1          30       0   41               1      5000000   
2088           1          30       0   44               1      5000000   
2089           1          30       0   47               1      5000000   

      Occupation  Smoker  
0              4       0  
1              2       1  
2              2       0  
3              4       1  
4              3       0  
...          ...     ...  
2085           2       1  
2086           2       1  
2087           2       1  
2088           5       0  
2089           5       0  

[2090 rows x 8 columns]

In [184]:
Y

0         2030.438032
1       302907.286978
2         8242.752196
3         2054.927549
4         6688.783291
            ...      
2085     13901.991000
2086     15403.823000
2087     18345.093000
2088     12751.397000
2089     16178.973000
Name: Total Premium, Length: 2090, dtype: float64

In [185]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(X,Y, test_size=0.2, random_state=2)

In [186]:
Regressor=XGBRegressor()
Regressor.fit(X,Y.values)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=4, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [187]:
Y_pred = Regressor.predict(X)

In [188]:
Y_pred

array([  1378.3346, 298053.34  ,   8414.334 , ...,  17162.06  ,
        13182.518 ,  16955.06  ], dtype=float32)

In [189]:
X = np.array([['Term',35,'Female',33,'Yearly',3500000,'Salaried','No']])
X

array([['Term', '35', 'Female', '33', 'Yearly', '3500000', 'Salaried',
        'No']], dtype='<U11')

In [190]:
X[:,0] = le_policytype.transform(X[:,0])
X[:,2] = le_gender.transform(X[:,2])
X[:,4] = le_premiumpayment.transform(X[:,4])
X[:,6] = le_occupation.transform(X[:,6])
X[:,7] = le_smoker.transform(X[:,7])
X = X.astype(float)
X

array([[1.0e+00, 3.5e+01, 0.0e+00, 3.3e+01, 1.0e+00, 3.5e+06, 2.0e+00,
        0.0e+00]])

In [191]:
Y_pred = Regressor.predict(X)
Y_pred

array([8414.334], dtype=float32)

In [192]:
import pickle

In [198]:
data = {"model":Regressor, "le_policytype":le_policytype, "le_gender":le_gender, "le_premiumpayment":le_premiumpayment, "le_occupation":le_occupation, "le_smoker":le_smoker}
with open('saved_steps.pkl','wb') as file:
    pickle.dump(data,file)

In [199]:
with open('saved_steps.pkl','rb') as file:
    data = pickle.load(file)
    
Regressor_Loaded = data["model"]
le_policytype = data["le_policytype"]
le_gender = data["le_gender"]
le_premiumpayment = data["le_premiumpayment"]
le_occupation = data["le_occupation"]
le_smoker = data["le_smoker"]

In [200]:
Y_pred = Regressor_Loaded.predict(X)
Y_pred

array([8414.334], dtype=float32)